name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Action Lint
        uses: panda0603/lint-action@1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
